#python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_5' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 5 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True
#python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_10' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 10 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True
#python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_20' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 20 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_40' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 40 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_60' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 60 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_80' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 80 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True
#python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_100' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 100 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True

python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_5_ng' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 5 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --mlp_cls 'identity'
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_10_ng' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 10 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --mlp_cls 'identity'
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_20_ng' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 20 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --mlp_cls 'identity'
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_40_ng' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 40 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --mlp_cls 'identity'
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_60_ng' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 60 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --mlp_cls 'identity'
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_80_ng' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 80 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --mlp_cls 'identity'
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_100_ng' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 100 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --mlp_cls 'identity'

python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_5_d16' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 5 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --d_model 16
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_10_d16' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 10 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --d_model 16
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_20_d16' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 20 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --d_model 16
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_40_d16' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 40 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --d_model 16
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_60_d16' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 60 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --d_model 16
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_80_d16' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 80 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --d_model 16
python tsp.py --save_loc 'checkpoints/gpu/tour_lightning/mamba2_100_d16' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 100 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True  --d_model 16
################################################################
python tsp.py --save_loc 'checkpoints/gpu/action_lightning/mamba2_5' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 5 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True --action 'next_city'
python tsp.py --save_loc 'checkpoints/gpu/action_lightning/mamba2_10' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 10 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True --action 'next_city'
python tsp.py --save_loc 'checkpoints/gpu/action_lightning/mamba2_20' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 20 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True --action 'next_city'
python tsp.py --save_loc 'checkpoints/gpu/action_lightning/mamba2_40' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 40 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True --action 'next_city'
python tsp.py --save_loc 'checkpoints/gpu/action_lightning/mamba2_60' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 60 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True --action 'next_city'
python tsp.py --save_loc 'checkpoints/gpu/action_lightning/mamba2_80' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 80 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True --action 'next_city'
python tsp.py --save_loc 'checkpoints/gpu/action_lightning/mamba2_100' --nb_layers 3  --nb_epochs 4 --val_split 5 --nb_batch_per_epoch 20 --city_count 100 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --reverse True --action 'next_city'
################################################################
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/standard_mamba2_5' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 5 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/standard_mamba2_10' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 10 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/standard_mamba2_20' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 20 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/standard_mamba2_40' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 40 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/standard_mamba2_60' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 60 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/standard_mamba2_80' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 80 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/standard_mamba2_100' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 100 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128

#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse1_mamba2_5' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 5 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_1'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse1_mamba2_10' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 10 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_1'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse1_mamba2_20' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 20 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_1'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse1_mamba2_40' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 40 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_1'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse1_mamba2_60' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 60 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_1'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse1_mamba2_80' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 80 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_1'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse1_mamba2_100' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 100 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_1'

#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse2_mamba2_5' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 5 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_2'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse2_mamba2_10' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 10 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_2'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse2_mamba2_20' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 20 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_2'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse2_mamba2_40' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 40 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_2'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse2_mamba2_60' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 60 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_2'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse2_mamba2_80' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 80 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_2'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse2_mamba2_100' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 100 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_2'

python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse5_mamba2_5' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 5 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_5'
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse5_mamba2_10' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 10 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_5'
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse5_mamba2_20' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 20 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_5'
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse5_mamba2_40' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 40 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_5'
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse5_mamba2_60' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 60 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_5'
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse5_mamba2_80' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 80 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_5'
python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse5_mamba2_100' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 100 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_5'

#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse10_mamba2_5' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 5 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_10'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse10_mamba2_10' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 10 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_10'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse10_mamba2_20' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 20 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_10'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse10_mamba2_40' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 40 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_10'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse10_mamba2_60' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 60 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_10'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse10_mamba2_80' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 80 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_10'
#python tsp.py --save_loc 'checkpoints/gpu/importance_sampling_lightning/Reuse10_mamba2_100' --nb_layers 1  --nb_epochs 4 --val_split 20 --test_split 4 --nb_batch_per_epoch 20 --city_count 100 --mamba2 True --pynvml True --gpu_id 0 --wandb --bsz 50 --d_model 128 --action 'importance_sampling_10'